version: '3.7'
services:
  its_hk_fe:
    container_name: ueno-system-fe
    image: ueno-system-fe
    build:
      dockerfile: Dockerfile
      context: .
      args:
        ACTIVE_PROFILE: ${ACTIVE_PROFILE:-stagging}
    #command: npm run start -- --dotenv .env.${ACTIVE_PROFILE}
    ports:
      - 60055:3000
    volumes:
      - ${UPLOAD_FOLDER:-/ueno_upload}:/src/static/upload