export const importSaleReturnSchema = {
  amount: 0,
  blance: 0,
  customerPO: 'string',
  description: 'string',
  inNO: 'string',
  inQuantity: 0,
  invoiceCode: 'string',
  invoiceDate: 'string',
  isExportAll: true,
  itemCode: 'string',
  itemName: 'string',
  language: 'string',
  pageNo: 0,
  pageSize: 0,
  price: 0,
  searchType: 'string',
  sortAscOrDesc: 'string',
  sortByColumn: 'string',
  unit: 'string',
}
