export const salePriceSchema = {
  apparelCode: 'string',
  companyName: 'string',
  currency: 'string',
  customerID: 0,
  customerPartsName: 'string',
  description: 'string',
  editDate: 'string',
  editUser: 'string',
  effectiveDate: 'string',
  exportAllData: true,
  isEnable: 0,
  itemCode: 'string',
  itemID: 0,
  itemName: 'string',
  language: 'string',
  maxQuantity: 'string',
  memo: 'string',
  minQuantity: 'string',
  pageNo: 0,
  pageSize: 0,
  price: 'string',
  searchType: 'string',
  sortAscOrDesc: 'string',
  sortByColumn: 'string',
  unit: 'string',
}
