export const statementSchema = {
  amount: 'string',
  currency: 'string',
  customerName: 'string',
  deliveryDate: 'string',
  editDate: 'string',
  editUser: 'string',
  exportAllData: true,
  language: 'string',
  memo: 'string',
  month: 'string',
  orderDate: 'string',
  orderNumber: 'string',
  pageNo: 0,
  pageSize: 0,
  payDate: 'string',
  searchType: 'string',
  sortAscOrDesc: 'string',
  sortByColumn: 'string',
  statementDate: 'string',
  statementNo: 'string',
  year: 'string',
  SOPriceIncludeTax: 'string',
  SOAmountIncludeTax: 'string',
  SODiscountRate: 'string',
  SOPriceIncludeDiscount: 'string'
}
