export default {
  computed: {
    dataHeader() {
      return [
        {
          fieldName: 'ItemCode',
          fieldOrder: '5',
          key: 'itemCode',
          fieldWide: '225',
          labelName: this.$t('lbl_ItemCode_0'),
          gridName: 'ItemViewGrid',
          hidden: false,
        },
        {
          fieldName: 'ItemName',
          fieldOrder: '6',
          key: 'itemName',
          fieldWide: '225',
          labelName: this.$t('lbl_ItemName_0'),
          gridName: 'ItemViewGrid',
          hidden: false,
        },
        {
          fieldName: 'Description',
          fieldOrder: '7',
          key: 'description',
          fieldWide: '225',
          labelName: this.$t('lbl_Description_0'),
          gridName: 'ItemViewGrid',
          hidden: false,
        },
        {
          fieldName: 'ItemType',
          fieldOrder: '2',
          key: 'itemType',
          fieldWide: '150',
          labelName: this.$t('lbl_ItemType_0'),
          gridName: 'ItemViewGrid',
          hidden: false,
        },
        {
          fieldName: 'Unit',
          fieldOrder: '10',
          key: 'unit',
          fieldWide: '120',
          labelName: this.$t('lbl_Unit_0'),
          gridName: 'ItemViewGrid',
          hidden: false,
        },
        {
          fieldName: 'Quantity',
          fieldOrder: '12',
          key: 'quantity',
          fieldWide: '150',
          labelName: this.$t('lbl_Quantity_0'),
          gridName: 'ItemViewGrid',
          hidden: false,
          default: true,
        },
        {
          fieldName: 'EffectiveDate',
          fieldOrder: '11',
          key: 'effectiveDate',
          fieldWide: '150',
          labelName: this.$t('lbl_EffectiveDate_0'),
          gridName: 'ItemViewGrid',
          hidden: false,
        },

        {
          fieldName: 'FailRate',
          fieldOrder: '13',
          key: 'failRate',
          fieldWide: '150',
          labelName: this.$t('lbl_FailRate_0'),
          gridName: 'ItemViewGrid',
          hidden: false,
          default: true,
        },

        {
          fieldName: 'WastageRate',
          fieldOrder: '14',
          key: 'subWastageRate',
          fieldWide: '150',
          labelName: this.$t('lbl_WastageRate_0'),
          gridName: 'ItemViewGrid',
          hidden: false,
          default: true,
        },

        {
          fieldName: 'Memo',
          fieldOrder: '14',
          key: 'memo',
          fieldWide: '250',
          labelName: this.$t('lbl_Memo_0'),
          gridName: 'ItemViewGrid',
          hidden: false,
          default: true,
        },
      ]
    },
  },
}
