export default {
  computed: {
    dataHeaderBox() {
      return [
        {
          id: 1,
          fieldName: 'BoxType',
          fieldOrder: 1,
          key: 'boxType',
          fieldWide: '145',
          hidden: false,
          labelName: this.$t('lbl_BoxType_0'),
        },
        {
          id: 2,
          fieldName: 'Long',
          fieldOrder: 2,
          key: 'boxLong',
          fieldWide: '145',
          hidden: false,
          labelName: this.$t('lbl_Long_0'),
        },
        {
          id: 3,
          fieldName: 'Width',
          fieldOrder: 3,
          key: 'width',
          fieldWide: '145',
          labelName: this.$t('lbl_Width_0'),
          hidden: false,
        },
        {
          id: 4,
          fieldName: 'Height',
          fieldOrder: 4,
          key: 'height',
          fieldWide: '145',
          labelName: this.$t('lbl_High_0'),
          hidden: false,
        },
        {
          id: 5,
          fieldName: 'CBM',
          fieldOrder: 5,
          key: 'cbm',
          fieldWide: '145',
          labelName: 'CBM',
          hidden: false,
        },
        {
          id: 6,
          fieldName: 'PackQty',
          fieldOrder: 6,
          key: 'packQty',
          fieldWide: '145',
          labelName: this.$t('lbl_PackQty_0'),
          hidden: false,
        },
        {
          id: 7,
          fieldName: 'Weight',
          fieldOrder: 7,
          key: 'weight',
          fieldWide: '145',
          labelName: this.$t('lbl_Weight_0'),
          hidden: false,
        },
        {
          id: 8,
          fieldName: 'WeightUnit',
          fieldOrder: 8,
          key: 'weightUnit',
          fieldWide: '145',
          labelName: this.$t('lbl_WeightUnit_0'),
          hidden: false,
        },
        {
          id: 9,
          fieldName: 'Unit',
          fieldOrder: 9,
          key: 'unit',
          fieldWide: '145',
          labelName: this.$t('lbl_Unit_0'),
          hidden: false,
        },
        {
          id: 9,
          fieldName: 'Capacity',
          fieldOrder: 10,
          key: 'capacity',
          fieldWide: '145',
          labelName: this.$t('lbl_Capacity_0'),
          hidden: false,
        },
        {
          id: 10,
          fieldName: 'Pallet',
          fieldOrder: 11,
          key: 'pallet',
          fieldWide: '145',
          labelName: this.$t('lbl_Pallet_0'),
          hidden: false,
        },
        {
          id: 11,
          fieldName: 'Memo',
          fieldOrder: 12,
          key: 'memo',
          fieldWide: '145',
          labelName: this.$t('lbl_Memo_0'),
          hidden: false,
        },
        {
          id: 12,
          fieldName: 'EditUser',
          fieldOrder: 13,
          key: 'editUser',
          fieldWide: '145',
          labelName: this.$t('lbl_EditUser_0'),
          hidden: false,
        },
        {
          id: 13,
          fieldName: 'EditDate',
          fieldOrder: 14,
          key: 'editdate',
          fieldWide: '145',
          labelName: this.$t('lbl_EditDate_0'),
          hidden: false,
        },
      ]
    },
  },
}
