export default {
  computed: {
    dataHeader() {
      return [
        {
          fieldName: 'OrderType',
          fieldOrder: '1',
          key: 'orderType',
          fieldWide: '100',
          labelName: this.$t('lbl_OrderType_0'),
          gridName: 'ItemViewGrid',
          hidden: false,
        },

        {
          fieldName: 'ItemType',
          fieldOrder: '2',
          key: 'itemType',
          fieldWide: '100',
          labelName: this.$t('lbl_ItemType_0'),
          gridName: 'ItemViewGrid',
          hidden: false,
        },

        {
          fieldName: 'OrderNumber',
          fieldOrder: '3',
          key: 'orderNO',
          fieldWide: '100',
          labelName: this.$t('lbl_OrderNO_0'),
          gridName: 'ItemViewGrid',
          hidden: false,
        },
        {
          fieldName: 'IsBad',
          fieldOrder: '4',
          key: 'isBad',
          fieldWide: '100',
          labelName: this.$t('lbl_IsBad_0'),
          gridName: 'ItemViewGrid',
          hidden: false,
        },
        {
          fieldName: 'ItemCode',
          fieldOrder: '5',
          key: 'itemCode',
          fieldWide: '100',
          labelName: this.$t('lbl_ItemCode_0'),
          gridName: 'ItemViewGrid',
          hidden: false,
        },
        {
          fieldName: 'ItemName',
          fieldOrder: '6',
          key: 'itemName',
          fieldWide: '150',
          labelName: this.$t('lbl_ItemName_0'),
          gridName: 'ItemViewGrid',
          hidden: false,
        },
        {
          fieldName: 'Description',
          fieldOrder: '7',
          key: 'description',
          fieldWide: '100',
          labelName: this.$t('lbl_Description_0'),
          gridName: 'ItemViewGrid',
          hidden: false,
        },
        {
          fieldName: 'LotNO',
          fieldOrder: '8',
          key: 'lotNO',
          fieldWide: '100',
          labelName: this.$t('lbl_LotNo_0'),
          gridName: 'ItemViewGrid',
          hidden: false,
        },
        {
          fieldName: 'RackNo',
          fieldOrder: '9',
          key: 'rackNo',
          fieldWide: '100',
          labelName: this.$t('lbl_RackNO_0'),
          gridName: 'ItemViewGrid',
          hidden: false,
        },
        {
          fieldName: 'Warehouse',
          fieldOrder: '10',
          key: 'warehouse',
          fieldWide: '100',
          labelName: this.$t('lbl_Warehouse_0'),
          gridName: 'ItemViewGrid',
          hidden: false,
        },
        {
          fieldName: 'TransateDate',
          fieldOrder: '11',
          key: 'transDate',
          fieldWide: '100',
          labelName: this.$t('lbl_TransDate_0'),
          gridName: 'ItemViewGrid',
          hidden: false,
        },
        {
          fieldName: 'Quantity',
          fieldOrder: '12',
          key: 'quantity',
          fieldWide: '100',
          labelName: this.$t('lbl_Quantity_0'),
          gridName: 'ItemViewGrid',
          hidden: false,
          default: true,
        },
        {
          fieldName: 'CostPrice',
          fieldOrder: '13',
          key: 'price',
          fieldWide: '100',
          labelName: this.$t('lbl_CostPrice_0'),
          gridName: 'ItemViewGrid',
          hidden: false,
          default: true,
        },

        {
          fieldName: 'Amount',
          fieldOrder: '14',
          key: 'amount',
          fieldWide: '100',
          labelName: this.$t('lbl_Amount_0'),
          gridName: 'ItemViewGrid',
          hidden: false,
          default: true,
        },
      ]
    },
  },
}
