export default {
  computed: {
    headerMockData() {
      return [
        {
          fieldName: 'PBOrderNO',
          fieldOrder: 1,
          fieldWide: 120,
          labelName: this.$t('lbl_PBOrderNO_0'),
          gridName: 'PayBrowse',
          hidden: false,
        },
        {
          fieldName: 'PBInvoiceNo',
          fieldOrder: 1,
          fieldWide: 120,
          labelName: this.$t('lbl_PBInvoiceNo_0'),
          gridName: 'PayBrowse',
          hidden: false,
        },
        {
          fieldName: 'PBCustomerName',
          fieldOrder: 1,
          fieldWide: 200,
          labelName: this.$t(`lbl_CustomerName_0`),
          gridName: 'PayBrowse',
          hidden: false,
        },
        {
          fieldName: 'PBCurrency',
          fieldOrder: 1,
          fieldWide: 90,
          labelName: this.$t(`lbl_Currency_0`),
          gridName: 'PayBrowse',
          hidden: false,
        },
        {
          fieldName: 'PBReceiveDate',
          fieldOrder: 1,
          fieldWide: 90,
          labelName: this.$t(`lbl_PayBrowseDate_0`),
          gridName: 'PayBrowse',
          hidden: false,
        },
        {
          fieldName: 'Amount',
          fieldOrder: 1,
          fieldWide: 90,
          labelName: this.$t(`lbl_TotalAmount_0`),
          gridName: 'PayBrowse',
          hidden: false,
        },
        {
          fieldName: 'ARAmount',
          fieldOrder: 1,
          fieldWide: 90,
          labelName: this.$t('lbl_ARAmount_0'),
          gridName: 'PayBrowse',
          hidden: false,
        },
        {
          fieldName: 'BlanceAmount',
          fieldOrder: 1,
          fieldWide: 90,
          labelName: this.$t('lbl_BlanceAmount_0'),
          gridName: 'PayBrowse',
          hidden: false,
        },
        {
          fieldName: 'Date',
          fieldOrder: 1,
          fieldWide: 90,
          labelName: this.$t('lbl_ARDate_0'),
          gridName: 'PayBrowse',
          hidden: false,
        },
        {
          fieldName: 'IsStop',
          fieldOrder: 1,
          fieldWide: 90,
          labelName: this.$t('lbl_IsStop_0'),
          gridName: 'PayBrowse',
          hidden: false,
        },
      ]
    },
  },
}
