export default {
  computed: {
    dataHeaderUser() {
      return [
        {
          id: 1,
          fieldName: 'LoginName',
          fieldOrder: 1,
          key: 'loginName',
          fieldWide: '217',
          hidden: false,
          labelName: this.$t('lbl_LoginName_0'),
        },
        {
          id: 2,
          fieldName: 'EmployeeName',
          fieldOrder: 2,
          key: 'employeeName',
          fieldWide: '217',
          hidden: false,
          labelName: this.$t('lbl_EmployeeName_0'),
        },
        {
          id: 3,
          fieldName: 'UserGroupName',
          fieldOrder: 3,
          key: 'userGroupNames',
          fieldWide: '217',
          labelName: this.$t('lbl_UserGroupName_0'),
          hidden: false,
        },
        {
          id: 4,
          fieldName: 'Enable',
          fieldOrder: 4,
          key: 'enable',
          fieldWide: '217',
          labelName: this.$t('lbl_IsEnable_0'),
          hidden: false,
        },
        {
          id: 3,
          fieldName: 'GoogleName',
          fieldOrder: 3,
          key: 'googleName',
          fieldWide: '217',
          labelName: 'GoogleName',
          hidden: false,
        },
        {
          id: 5,
          fieldName: 'Memo',
          fieldOrder: 5,
          key: 'memo',
          fieldWide: '217',
          labelName: this.$t('lbl_Memo_0'),
          hidden: false,
        },
        {
          id: 6,
          fieldName: 'EditUser',
          fieldOrder: 6,
          key: 'editUser',
          fieldWide: '217',
          labelName: this.$t('lbl_EditUser_0'),
          hidden: false,
        },
        {
          id: 7,
          fieldName: 'EditDate',
          fieldOrder: 7,
          key: 'editDate',
          fieldWide: '217',
          labelName: this.$t('lbl_EditDate_0'),
          hidden: false,
        },
      ]
    },
  },
}
