export const purchasePriceSchema = {
  allExport: true,
  apparelCode: 'string',
  currency: 'string',
  description: 'string',
  editUser: 'string',
  editdate: 'string',
  effectiveDate: 'string',
  isEnable: true,
  itemCode: 'string',
  itemName: 'string',
  language: 'string',
  maxQuantity: 0,
  memo: 'string',
  minQuantity: 0,
  pageNo: 0,
  pageSize: 0,
  price: 0,
  searchType: 'string',
  sortAscOrDesc: 'string',
  sortByColumn: 'string',
  supPartsName: 'string',
  supplierName: 'string',
  unit: 'string',
}
