export default {
  prefix() {
    return '/base'
  },
  getCustomerList: (state) => state.customerList,
  getCompanyTypeOptions: (state) => state.companyTypeOptions,
  getUnitOptions: (state) => state.unitOptions,
  getWarehouseOptions: (state) => state.warehouseOptions,
  getCurrencyOptions: (state) => state.currencyOptions,
  getItemCodeOptions: (state) => state.itemCodeOptions,
  getCustomerNameList: (state) => state.customerNameList,
  getDepartmentOptions: (state) => state.departmentOptions,
  getEmployeeOptions: (state) => state.employeeList,
  getListBox: (state) => state.listBoxes,
  getPaymentTypeOptions: (state) => state.paymentTypeOptions,
  getColorOptions: (state) => state.colorOptions,
  getItemCustomOptions: (state) => state.itemCustomOptions,
  getNationIDOptions: (state) => state.nationIDOptions,
  getBornPlaceOptions: (state) => state.bornPlaceOptions,
  getDegreeIDOptions: (state) => state.degreeIdOptions,
  getPositionOptions: (state) => state.positionOptions,
  getPayTypeOptions: (state) => state.payTypeOptions,
  getStateOptions: (state) => state.stateOptions,
  getHostelOptions: (state) => state.hostelOptions,
  getLeaveReasonOptions: (state) => state.leaveReasonOptions,
  getWeightUnitOptions: (state) => state.weightUnitOptions,
  getUserGroupOptions: (state) => state.userGroupOptions,
  getShareTypeOptions: (state) => state.shareTypeOptions,
  getApparelOptions: (state) => state.apparelCodeOptions,
  getItemTypeOptions: (state) => state.itemTypeOptions,
  getOperationTypeOptions: (state) => state.operationTypeOptions,
  getLanguage: (state) => state.language,
  getMenuSidebar: (state) => state.menuSidebar,
  getActiveButtonToolBar: (state) => state.dataActiveButton,
  getPalletOptions: (state) => state.palletOptions,
  getLoading: (state) => state.isLoading,
  getListBox1: (state) => state.listBox1,
  getListBox2: (state) => state.listBox2,
  getListBox3: (state) => state.listBox3,
  getListBox4: (state) => state.listBox4,
  getListBox5: (state) => state.listBox5,
  getListBox6: (state) => state.listBox6,
  getInspectionTypes: (state) => state.inspectionTypes,
  getListBox8: (state) => state.listBox8,
  getListBox9: (state) => state.listBox9,
  getListBox10: (state) => state.listBox10,
  getListBox11: (state) => state.listBox11,
  getListBox12: (state) => state.listBox12,
  getListCOCustom1: (state) => state.listCOCustom1,
  getListCOCustom2: (state) => state.listCOCustom2,
  getListProcessStatus: (state) => state.listProcessStatus,
  getProcessStatus: (state) => state.processStatus,
  getSmaPriApiUrl: (state) => state.smaPriApiUrl,
  getListAccountingItems: (state) => state.listAccountingItems,
  getListCurrentAssets: (state) => state.listCurrentAssets,
}
