export const attachmentBrowseSchema = {
  address: 'string',
  editDate: 'string',
  editUser: 'string',
  fileName: 'string',
  fileSize: 'string',
  fileType: 'string',
  id: 0,
  isExport: true,
  language: 'string',
  lineID: 0,
  memo: 'string',
  moduleName: 'string',
  orderNO: 'string',
  pageNo: 0,
  pageSize: 0,
  searchType: 'string',
  sortAscOrDesc: 'string',
  sortColumn: 'string',
}
