export const companySchema = {
  subID: 1,
  companyCode: 'string',
  companyName: 'string',
  englishName: 'string',
  shortName: 'string',
  legalName: 'string',
  address1: 'string',
  address2: 'string',
  address3: 'string',
  addressEN1: 'string',
  addressEN2: 'string',
  addressEN3: 'string',
  tel: 'string',
  fax: 'string',
  webPage: 'string',
  email: 'string',
  postCode: 'string',
  currencyID: 3,
  bank: 'string',
  accountNo: 'string',
  memo: 'string',
  logo: 'string',
  editUser: 'string',
  editDate: 'string',
  file: null,
}
